### ISSUE TITLE
"output: lazyhtml_document" in YAML header causes error

### ISSUE THREAD

**Issue by pkopps** [hafen/lazyrmd#4]
On a windows machine:

R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lazyrmd_0.1.0 ROracle_1.2-2 DBI_0.4-1    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.5      knitr_1.13       magrittr_1.5     devtools_1.12.0  munsell_0.4.3    colorspace_1.2-6 R6_2.1.2         stringr_1.0.0    httr_1.2.1  
[10] plyr_1.8.4       tools_3.3.0      grid_3.3.0       gtable_0.2.0     git2r_0.15.0     withr_1.0.2      htmltools_0.3.5  yaml_2.1.13      digest_0.6.10  
[19] ggplot2_2.1.0    htmlwidgets_0.7  curl_0.9.7       memoise_1.0.0    evaluate_0.9     rmarkdown_1.0    stringi_1.1.1    scales_0.4.0  

When I add "lazyhtml_document" to "output:" in header of my .Rmd file and click Knit in RStudio I get this error:

Error in eval(expr, envir, enclos) : object 'lazyhtml_document' not found
Calls: <Anonymous> -> create_output_format -> eval -> eval
Execution halted

I reinstalled rmarkdown package, updated R and RStudio, installed the lazyrmd package from CRAN, github, and the 3rd location, but now luck

I feel like I am missing something big and apologize in advance if I am using this wrong, I am fairly new to rmarkdown and R

P.S. I also noticed @ https://cran.r-project.org/web/packages/lazyrmd/vignettes/lazy_example.html I get an error

![capture](https://cloud.githubusercontent.com/assets/12619201/17627982/41522f82-6081-11e6-95b1-47a61e267902.PNG)

Thanks in advance, I look forward to your response, this package has the potential to improve the painfully slow loading time (+30 seconds) of a 200+ chunk html output file of predominantly htmlwidgets

**Comment by hafen** [comment]
Thanks for the report.  @schloerke, can you look into this?

**Comment by schloerke** [comment]
Sure! Only have a Mac, but this should be fixed!

**Comment by hafen** [comment]
@schloerke can you try a document with clicking "Knit" in RStudio?  May not be mac-specific.

@pkopps perhaps likewise you could try rendering the document from the console using rmarkdown's `render()` method?

The second part of the problem (errors on this page: https://cran.r-project.org/web/packages/lazyrmd/vignettes/lazy_example.html) should also be investigated.

**Comment by schloerke** [comment]
@pkopps  I was able to reproduce the error.  

When building an Rmd file, if the package is not loaded in general (such as knitr, which also loads markdown), it must be specified with a "PACKAGENAME::function".  

When my header looks like:

``` yaml
---
title: "lazyrmd example"
author: Barret Schloerke
output: lazyhtml_document
---
```

I receive the error:

```
Error in eval(expr, envir, enclos) : object 'lazyhtml_document' not found
Calls: <Anonymous> -> create_output_format -> eval -> eval
Execution halted
```

If I include the lazyrmd::lazyhtml_document hook...

``` yaml
---
title: "lazyrmd example"
author: Barret Schloerke
output: lazyrmd::lazyhtml_document
---
```

... everything works as expected.

Please let me know if this does not solve your issue! :-)
- Barret

**Comment by pkopps** [comment]
This does solve my issue. Both the render() function and clicking the "Knit" button in RStudio with "output: lazyrmd::lazyhtml" in header work great. Thanks so much for the help, and again great work on this package, it is super useful
