### ISSUE TITLE
Lazy load vignette missing files on CRAN

### ISSUE THREAD

**Issue by schloerke** [hafen/lazyrmd#5]
(#4 missing html doc in pkg vig on CRAN)

Good news is that the lazy load works locally.

Bad news is that lazy load creates a separate html file which is not stored with the vignettes.  

If you visit https://cran.r-project.org/web/packages/lazyrmd/vignettes/ you can see there are no subdirectories.  There should at least be the "lazy_widgets" dir and it's js  and html files.  If you download the source tarball, all the files exist like the should and everything is great.  CRAN is not loading the inst dir as the vignettes dir.  Very confusing.

First thoughts... 
- we figure out how to recursively html parse... Seems too hard
- Change the output / javascript to be a "lazy load" javascript only.  
  - It could still have the same javascript content as a regular widget, but a javascript hook to not load.  
  - This route seems more like a pull request for html widgets.  IDK for sure

@hafen Thoughts?
- Barret

**Comment by hafen** [comment]
I'm not sure I follow the options here.  Could you elaborate?

**Comment by schloerke** [comment]
Looking at the javascript version... recliner.js allows for a "on focus" method. So when the div becomes in focus, we could trigger a static render of the html widget.  The trick is to get it to not render at the beginning.  

I'm close to getting this method to work.  

Pros:
- This will prevent independent iframes of content being generated
- only need one copy of the html widget js file, not one for every lazy html widget

Cons: 
- all data will now be in the html file (but not all loaded at once)

**Comment by hafen** [comment]
If I'm not mistaken, this will defeat the purpose of the package.  If we have to stick everything into one file, that will make the load time of the page really slow.  We need to defer not only the rendering, but also the loading of the resources for what is being rendered.

**Comment by hafen** [comment]
Actually I suppose if you can guarantee that all the widget stuff will be loaded last and that everything else will render fine immediately (including css, etc.), then this would be really nice as the lazy rendering would be faster since all the resources would eventually be loaded...

**Comment by schloerke** [comment]
staying with loading iframes
